version = "2"

[linters]
default = "all"
disable = [
  "wsl",
  "depguard",
  "wrapcheck",
  "revive",
  "noinlineerr",
  "nilnil",
  "ireturn",
  "godox",
  "gochecknoinits",
  "gochecknoglobals",
  "exhaustruct",
  "paralleltest",
  "varnamelen",
  "funlen"
]

[linters.exclusions]
paths = [
  "internal/infrastructure/sqlc",
  "test/mock"
]

[[linters.exclusions.rules]]
path = "_test\\.go"
linters = [
  "err113",
  "errcheck",
  "funlen",
  "noctx"
]

[[linters.exclusions.rules]]
path = "internal/domain/vo/error.go"
linters = [
  "mnd",
]
