version = "2"

[linters]
default = "all"
disable = [
  "wsl",
  "depguard",
  "wrapcheck",
  "revive",
  "noinlineerr",
  "nilnil",
  "ireturn",
  "godox",
  "gochecknoinits",
  "gochecknoglobals",
  "exhaustruct",
  "paralleltest",
  "varnamelen"
]
